### ISSUE TITLE
Is it possible to publish the 15.0 pre-release version to npm?

### ISSUE THREAD

**Issue by firedigger** [Romanchuk/angular-i18next#100]
Hello, thanks for developing this awesome package.
I have recently created a Angular 15 application and wanted to include translations.
The current version 14.2 with some minimal changes from your 14.2..15.0 it works perfectly but of course I can not use it in docker deployment due to version 15.0 not being published to npm. I understand that the 15.0 might not be ready for the release, but is it possible to publish it to npm as a pre-release package? Like -rc1 or something. So that Angular 15 users can develop around it awaiting the release. Thanks in advance.

**Comment by Romanchuk** [comment]
@firedigger Hello, it is already released ```15.0.0-0```

**Comment by firedigger** [comment]
You are correct, that is my blindness, https://www.npmjs.com/package/angular-i18next/v/15.0.0-0
Sorry for the bother
