### ISSUE TITLE
Interpolation is not working anymore

### ISSUE THREAD

**Issue by NiDeWe** [Romanchuk/angular-i18next#101]
Hi, It looks like the interpolation doesn't work anymore since the last update

`   <div *ngIf="control.errors['maxlength']" class="e-error">
        {{ 'form.format.length' | i18next : { max: control.errors['maxlength'].requiredLength } }}
    </div>`

in my language files, i have the next value: 
` "form": {
        "format": {
            "numbers": "Dit veld mag alleen maar cijfers bevatten",
            "length": "Dit veld mag maximum {{max}} karaters bevatten"
        }
}`

in the template when running, it just says : "Dit veld mag maximum {{max}} karaters bevatten"
the max parameter is not resolved.

**Comment by NiDeWe** [comment]
We found that the error is in the next file starting from line 58:
https://github.com/Romanchuk/angular-i18next/blob/9674cec8289e53448fe67c24cd543153bcb558a9/libs/angular-i18next/src/lib/I18NextService.ts#L58

the options are given as the default value...

**Comment by prhc-marco** [comment]
I made a fix that works for me locally, but I don't know if that's the best solution. We had the same problem in our application.

**Comment by Romanchuk** [comment]
@NiDeWe @prhc-marco Thank you, both! Try v15.0.5

**Comment by prhc-marco** [comment]
I tested a moment ago and it's works for my application
