### ISSUE TITLE
Property 'initialized' in type 'I18NextEvents' is not assignable to the same property in base type 'ITranslationEvents'.

### ISSUE THREAD

**Issue by guptmay02** [Romanchuk/angular-i18next#103]
![image](https://user-images.githubusercontent.com/89076785/217230264-3903f406-b34e-413e-a6c6-a676260ea3c5.png)
![image](https://user-images.githubusercontent.com/89076785/217230372-dfab87a2-2971-4b38-a49b-6650f926def0.png)

**Comment by vardana-bh** [comment]
Same error getting for v14.2.0

**Comment by Romanchuk** [comment]
Hello!
This was fixed in v15 #97 

In 14.2.0 you can temporary enable ```"skipLibCheck": true```

**Comment by Romanchuk** [comment]
@vardana-bh Yes, this also can help

**Comment by Romanchuk** [comment]
Done in #97
