### ISSUE TITLE
Integration to Angular 16

### ISSUE THREAD

**Issue by hannahths7** [Romanchuk/angular-i18next#109]
The installation on angular 16 is not possible because only angular/common <16.0.0 is accepted. Are there possible updates there in the future?

**Comment by Romanchuk** [comment]
it will be

**Comment by JacobF7** [comment]
@Romanchuk - thank you for this. Do we have an ETA for when Angular 16 will be supported?

**Comment by Romanchuk** [comment]
@JacobF7 I can do stuff for this project only in a free time. And it is now

**Comment by Romanchuk** [comment]
@JacobF7 Please try it out and tell me if it is ok: ```angular-i18next 16.0.0-0 published 🎉```

**Comment by JacobF7** [comment]
> @JacobF7 Please try it out and tell me if it is ok: `angular-i18next 16.0.0-0 published 🎉`

All seems to be working, thank you.

**Comment by Romanchuk** [comment]
@JacobF7 Also Readme.md updated. I have added hint on how to make older **angular-i18next** work with newer angular versions.

https://github.com/Romanchuk/angular-i18next#what-to-do-if-

```

# New angular version released, but angular-i18next is not released YET!!!

Angular releases mostly don't break angular-i18next, but we cannot tell ahead that current version of `angular-i18next` will work correctly with latest angular version.

You can override an angular-i18next `peerDependencies` in your `package.json` on your **own risk**:

```json
"overrides": {
  "angular-i18next": {
    "@angular/common": "*",
    "@angular/core": "*",
    "@angular/platform-browser": "*"
  }
}
```

**Comment by Romanchuk** [comment]
@JacobF7 Yes, i'll check out every PR today. Might not merge every right away without questions, but certainly ask some if they appear

**Comment by Romanchuk** [comment]
@JacobF7 

```angular-i18next 16.0.0 published 🎉```

It also includes **your PR**

Changelog:

https://github.com/Romanchuk/angular-i18next/releases/tag/v16.0.0
