### ISSUE TITLE
angular version issue

### ISSUE THREAD

**Issue by PramodCateina** [Romanchuk/angular-i18next#111]
i am using angular version Angular CLI: 12.2.18
 facing this error 
 Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Generic type 'ɵɵPipeDeclaration' requires 2 type argument(s).
![oie_eEiDM90izNWt (1)](https://github.com/Romanchuk/angular-i18next/assets/135108174/85116564-d18b-4d3b-abdc-b9e44e84de67)

**Comment by Romanchuk** [comment]
@PramodCateina Hello, i have no idea. If you use cli v12 you should use compatible angular-i18next version.
