### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by httpete** [Romanchuk/angular-i18next#13]
Hi,

I see some of my clients dying on the russian characters you have with the error "unexpected token". Can these be removed?

**Comment by httpete** [comment]
// Не подставлять namespace, если он уже указан в ключе

is there a few times

**Comment by Romanchuk** [comment]
@httpete ok, i will change all comments to english in a new release

**Comment by Romanchuk** [comment]
@httpete i've removed russian comments and released version 3.3.0. Check it out

**Comment by httpete** [comment]
nope we good now I haven't seen it since.
