### ISSUE TITLE
Typing for I18NextFormatPipe only takes string?

### ISSUE THREAD

**Issue by httpete** [Romanchuk/angular-i18next#15]
We use the i18next formatter to format Date objects (and pass it other types) why did you only allow values to be strings? We clearly want number formatting - the examples from i18next show type detection in the formatter function configured...

export declare class I18NextFormatPipe implements PipeTransform {
    private translateI18Next;
    constructor(translateI18Next: ITranslationService);
    transform(value: string, options: Object | string): string;
}

**Comment by httpete** [comment]
@Romanchuk  any thoughts on this? I think this will block people.

**Comment by httpete** [comment]
I see that you copied their type, I think they were wrong too.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25181

**Comment by Romanchuk** [comment]
@httpete  Sorry, had no time to answer.
Yes, i use string type for value derrived from these types. You are right, value can be an any type.
There would no problem to fix it for me, because i call format throught call function that is not typed.
I'm going to update package in a week (with this fix and i18next v11 support)

**Comment by httpete** [comment]
To be more correct, I think restricting it to one of the few would be better:

value: string | Date | Int

**Comment by httpete** [comment]
I don't see this in 3.4.1.

```
import { PipeTransform } from '@angular/core';
import { ITranslationService } from './ITranslationService';
export declare class I18NextFormatPipe implements PipeTransform {
    private translateI18Next;
    constructor(translateI18Next: ITranslationService);
    transform(value: string, options: Object | string): string;
}

```

**Comment by Romanchuk** [comment]
@httpete my fault, i will fix it today

**Comment by Romanchuk** [comment]
@httpete finally, done)

**Comment by httpete** [comment]
thanks Romanchuk! Just for anyone else watching, I was trying to utilize the angularCompilerOption:

        "fullTemplateTypeCheck": true,

which was failing on i18next format pipes (correctly since it was set as string) and after this update, it's perfect. Thank you!
