### ISSUE TITLE
Angular v6 and rxjs v6 support 

### ISSUE THREAD

**Issue by Romanchuk** [Romanchuk/angular-i18next#16]

**Comment by johnnykang** [comment]
hi, 
any roadmap/timeline to have the lib to support ng6?

**Comment by Romanchuk** [comment]
@johnnykang sorry, i was on vacation. Plan is to start work in this week.

**Comment by johnnykang** [comment]
no problem. I have fork the repo and make the fix on my local branch. so, all good for me for now. :)
