### ISSUE TITLE
Implement most methods of i18next API

### ISSUE THREAD

**Issue by Romanchuk** [Romanchuk/angular-i18next#17]

**Comment by WebStew** [comment]
Hi @Romanchuk ,

I presume this is why the `i18next.dir ()` method is not available - is that correct or am I missing something in the docs?

**Comment by Romanchuk** [comment]
@WebStew Hi, you are correct. angular-i18next started from my real project so i implemented and passed through only methods that i used. That is why angular-i18next misses many API methods.
You can suggest methods that you really need to implement them in first place.
