### ISSUE TITLE
Unit Test Documentation

### ISSUE THREAD

**Issue by WebStew** [Romanchuk/angular-i18next#18]
Hi @Romanchuk ,

Would you be able to provide documentation on how you would unit test a component using the i18next translation. I looked in the demo app repo but couldn't see any examples.

Do you mock the entire service and pipe?

**Comment by Romanchuk** [comment]
@WebStew Actually i have no unit tests for components that use i18next =(
The simpliest and easiest way (as i know) for any tests is to setup i18next with 'cimode' language.
[https://www.i18next.com/how-to/faq](https://www.i18next.com/how-to/faq
)
> **How to handle with changes in e2e tests?**
> 
> For e2e tests a good tactic is to set language to cimode on init. This will set i18next to always return the key on calling i18next.t. Want to add the namespace to returned value change appendNamespaceToCIMode: true on init.

Or you can stub "ITranslationService" for achieve specific behavior.

**Comment by ArturKwiatkowski** [comment]
It would be super nice if you could throw an example spec for a component. I am still figuring this all out, maybe I'll propose a PR if I succeed.

**Comment by Romanchuk** [comment]
@WebStew @ArturKwiatkowski Hi! I just added exaple spec of in-project unit-testing 
[/tests/projectTests/projectTests.spec.ts](https://github.com/Romanchuk/angular-i18next/blob/master/tests/projectTests/projectTests.spec.ts)

Hope, this will help you.

**Comment by duPleX93** [comment]
Hello Romanchuk!
Unfortunatelly your example does not help to me :/
Can you give some advice pls, what did I do wrong?

When I run my test file, i get 2 errors:
1.) NullInjectorError: No provider for InjectionToken I18NEXT_SERVICE!
2.) Error: The pipe 'i18next' could not be found!

And my Test file:
`export function appInit(i18next: ITranslationService) {
  return () => {
    const promise: Promise<I18NextLoadResult> = i18next
      .init({
        debug: true,
        lng: 'cimode'
      });
    return promise;
  };
}

export function localeIdFactory(i18next: ITranslationService)  {
  return i18next.language;
}

export const I18N_PROVIDERS = [
  {
    provide: APP_INITIALIZER,
    useFactory: appInit,
    deps: [I18NEXT_SERVICE],
    multi: true
  },
  {
    provide: LOCALE_ID,
    deps: [I18NEXT_SERVICE],
    useFactory: localeIdFactory
  },
];


describe('NavComponent', () => {
  let component: NavComponent;
  let fixture: ComponentFixture<NavComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        BrowserModule,
        UiElementsModule,
        RouterTestingModule,
        HttpClientModule,
        BrowserAnimationsModule,
        MatExpansionModule,
        I18NextModule.forRoot()
      ],
      declarations: [ NavComponent ],
      providers: [
        { provide: 'environment', useValue: environment },
        { provide: UserManagerService, useClass: MockUserManagerService },
        I18N_PROVIDERS
      ],
    })
    .compileComponents();
  });`

**Comment by tihomir-horvat-fadv** [comment]
> @WebStew @ArturKwiatkowski Hi! I just added exaple spec of in-project unit-testing [/tests/projectTests/projectTests.spec.ts](https://github.com/Romanchuk/angular-i18next/blob/master/tests/projectTests/projectTests.spec.ts)
> 
> Hope, this will help you.

And this link is broken. I need to use this library as part of current project dependency, unfortunately there is no documentation for testing beside of this comment. Also It would be nice to have your code and examples covered with unit tests.
