### ISSUE TITLE
Initialization with XHR Backend result in undefined Keys message

### ISSUE THREAD

**Issue by drdreo** [Romanchuk/angular-i18next#19]
I am struggling with accessing the translation ressources from the backend. Using the pipe outputs an undefined message.
The debug message: `i18next::translator: missingKey undefined translation test test`
I used the pipe like:
` <p>{{'test' | i18next}}</p>`

When i use angular-18next without the backend property and directly insert ressources it works perfectly fine.
But since the XHR is async, i think this creates the problem.
The order of messages logged to console is:

1. i18next::translator: missingKey undefined translation test test
2. i18next::backendConnector: loaded namespace translation for language en 
3. i18next: initialized 

So it first tries to find the key, which is not yet fetched from the backend, then it gets the translations and afterwards i see all my translations in the console. The markup still displays the translation key.

How can i tell the pipe to wait until translations are loaded, or what would be a better approach to get the translations from a backend server? Right now the server just returns the .json file on a request like "/locales/en".

I am using Google Chrome on Windows 10, 

- "angular-i18next": "^4.0.0-beta",
- "angular": "^6.0.3",
- "i18next": "^11.3.3",
-  "i18next-xhr-backend": "latest",

### My Configuration in Angular 6:
```
import { Component, Inject } from '@angular/core';
import { I18NEXT_SERVICE, ITranslationService } from 'angular-i18next';
import Backend from 'i18next-xhr-backend';
import * as i18nextLanguageDetector from 'i18next-browser-languagedetector';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  constructor( @Inject(I18NEXT_SERVICE) private i18NextService: ITranslationService ){
    i18NextService
      .use(Backend)
      .use(i18nextLanguageDetector)
      .init({
        backend: {
          // path to post missing resources
          addPath: "http://localhost:4000/locales/{{lng}}/{{ns}}.missing.json",
          // jsonIndent to use when storing json files
          jsonIndent: 2,
          // path where resources get loaded from
          loadPath: "http://localhost:4000/locales/{{lng}}/{{ns}}.json"
        },
        whitelist: ['en'],
        fallbackLng: 'en',
        debug: true,
        returnEmptyString: false,
      });
  }
}
```

**Comment by Romanchuk** [comment]
@drdreo Hi, did you tried method described in a [Cookbook](https://github.com/Romanchuk/angular-i18next#initialize-i18next-before-angular-application)


Here is example in demo app:
https://github.com/Romanchuk/angular-i18next-demo/blob/master/src/app/AppModule.ts

**Comment by Romanchuk** [comment]
@drdreo Any news?

**Comment by drdreo** [comment]
I couldn't try yet. Due to i had a deadline, i switched to a different library.
But thank you for your time.

**Comment by Romanchuk** [comment]
Closed due no info
