### ISSUE TITLE
I18next pipe not available for components in common module

### ISSUE THREAD

**Issue by WebStew** [Romanchuk/angular-i18next#20]
Hi @Romanchuk 

I have the following NG modules in my application :

My Shared module
`@NgModule ({
	declarations : [
		SomeCommonComponent
		...
	] ,
	exports : [
		SomeCommonComponent
		...
	] ,
	imports : [
		BrowserModule
	]
})`

My Core module where I import the I18Next and my shared module above
`@NgModule ({
	imports : [
		MySharedModule ,
		I18NextModule.forRoot ()
	] ,
	providers : [
		CoreServices
		...
	]
})`

My application module
`@NgModule ({
	bootstrap 	: [
		ApplicationComponent
	] ,
	imports : [
		CoreModule
	] ,
	declarations : [
		ApplicationComponent
	]
})`

The problem I am having is that the i18next pipe is not available to my components in MySharedModule. Do I need to export the pipe or something?

**Comment by Romanchuk** [comment]
@WebStew  My guess is that you missing import of I18NextModule (without forRoot calling) in module where you trying to use pipe.
Also note that forRoot call must be single in whole app and it must be placed in a root module (whenever you name it =) ).

**Comment by WebStew** [comment]
Thanks @Romanchuk. So probably include I18NextModule in all modules that use the pipe but only call forRoot () in a single high level module?

**Comment by Romanchuk** [comment]
@WebStew Right, that is exactly what i tried to say =)
