### ISSUE TITLE
Question : Is it possible to load resources from init options and if not available load from XHR

### ISSUE THREAD

**Issue by WebStew** [Romanchuk/angular-i18next#22]
Hi @Romanchuk ,

Is it possible to load some translation resources within the init options when the application starts and later when a route change happens - load in additional translation files with backend-xhr plugin?

It seems you can only do one or the other and not both?

**Comment by Romanchuk** [comment]
This question should be directed to i18next maintainers. But i can try to anwser)
> It seems you can only do one or the other and not both?
Yes, I guess you can't do both with just i18next options setup.
I think you can try to do it manualy:
1) Set initial translation resources
2) In the moment you want to load additional translation files you can:
a) try to reload recources: https://www.i18next.com/overview/api#reloadresources
b) or your initial lang can be some 'service_lang' and after init you just load a real language
https://www.i18next.com/overview/api#loadlanguages
c)  just do http request for .json you need, handle it and call addResourceBundle to add lang.
