### ISSUE TITLE
Suggestion for doc fix

### ISSUE THREAD

**Issue by httpete** [Romanchuk/angular-i18next#23]
Hi,

import { I18NextPipe } from './I18NextPipe';

You have this in the example about "using it in your code" I think you want:

import { I18NextPipe } from 'angular-i18next';

This has bitten many devs here.  Can you explain a bit more why we should inject the pipe vs the service into component controllers?

**Comment by Romanchuk** [comment]
@httpete Thanks, you are right! Done!

`This has bitten many devs here. Can you explain a bit more why we should inject the pipe vs the service into component controllers?`

Pipe has more features:


I should update docs

> Warning: Injection of I18NextService is possible, but it would not consider I18NEXT_NAMESPACE and I18NEXT_SCOPE providers. There are 2 possible reasons to inject I18NextService: initialization and subscription to its events. In all other cases inject I18NextPipe.

**Comment by Romanchuk** [comment]
@httpete Thanks, you are right! Done!

`This has bitten many devs here. Can you explain a bit more why we should inject the pipe vs the service into component controllers?`

It's not obligatory. It's just a recommendation.

I18NextService is just a wrapper for original i18next. So if you want for instance translate and format you'll do it in two steps (via original i18next or I18NextService):
`18next.format(i18next.t('world_key'),  'uppercase')  // -> WORLD`

It gives you possibility to pass format as option parameter and do it in one step:
`{ "world_key": 'world' }`
`I18NextPipe.transform('world_key', { format: 'cap' }) // -> World`
`{{ 'world_key' | i18next: { format: 'cap' } }} // -> World`

In many cases you might need to capitalize translated value (dialogs, toastr/snackbar, translate third-party controls etc.) in code. Simplest way to achieve that is to inject I18NextCapPipe and call transform (it will translate and apply `format: 'cap'`). 

When you use both pipe and service for translations in components it looks ambiguous and strange. So i prefer to choose single way to translate in code.
