### ISSUE TITLE
I18NextService.loadLanguages calling down to i18next.loadNamespaces

### ISSUE THREAD

**Issue by fatboystring** [Romanchuk/angular-i18next#28]
Hi, thanks for the library.

I am trying to use the `I18NextService.loadLanguages` method in my app to load a new language on user request in my app.  On doing so I see the following in my debug logs (in the browser console).

`i18next::backendConnector: loaded namespace de for language en`

On further investigation I see that the `I18NextService.loadLanguages` method actually calls down to `i18next.loadNamespaces`:

https://github.com/Romanchuk/angular-i18next/blob/master/src/I18NextService.ts#L95

I was wondering if this is an oversight or if I'm missing something?  I'd be happy to update the code and submit a PR if it helps.

**Comment by Romanchuk** [comment]
@fatboystring Hi, for sure it's a stupid missprint.
You are welcome to make a PR or i will fix it next week

**Comment by fatboystring** [comment]
Hi @Romanchuk many thanks.  I've opened a PR here.

https://github.com/Romanchuk/angular-i18next/pull/29

Let me know if you think anything else needs updating

**Comment by Romanchuk** [comment]
Thank you for PR!
Fixed in 6.0.1
