### ISSUE TITLE
Question: warning in the readme regarding i18next-xhr-backend@3.0.0

### ISSUE THREAD

**Issue by DmitryEfimenko** [Romanchuk/angular-i18next#33]
There is a warning in the readme:

> If you use "i18next-xhr-backend" plugin make sure it's version less than 3.0.0 (version 3.0.0 is not working properly)

Could you please provide more details? What's not working? I didn't see this message and installed 3.0.0. It seems to work, but maybe I'm missing something.

**Comment by Romanchuk** [comment]
Hi, my collegue updated i18next-xhr-backend in project to 3.0.0 and translation stoped loading. After moving back to latest v2 it worked.
I didn't deep dive to this issue. May be some settings changed or smthng

Do you use v3 on a new project or just updated?

**Comment by DmitryEfimenko** [comment]
v3 on a new project

**Comment by Romanchuk** [comment]
@DmitryEfimenko ok, i'm going to figure it out. To be sure if v3 is safe to use

**Comment by Romanchuk** [comment]
@DmitryEfimenko Just check it out.
i18next-xhr-backend is safe for work, it's just changed import style

Updated demo
https://romanchuk.github.io/angular-i18next-demo/

**Comment by Romanchuk** [comment]
Also i18next must be at least v 17.0.8 - earlier versions has broken typings and conflicts with i18next-xhr-backend v3
