### ISSUE TITLE
Is i18next's context differentiation supported?

### ISSUE THREAD

**Issue by david-bulte** [Romanchuk/angular-i18next#34]
Hi, is this feature supported: https://www.i18next.com/translation-function/context?

If yes, I couldn't get it to work. Should we add a specific configuration for this?

Thanks

**Comment by Romanchuk** [comment]
@david-bulte  Hi, there is nothing specific about it in angular-i18next. It should work as original i18next

**Comment by david-bulte** [comment]
Sorry, my (stupid) mistake. It works as expected. Thanks again.
