### ISSUE TITLE
I see low activity here

### ISSUE THREAD

**Issue by scastaldi** [Romanchuk/angular-i18next#36]
Hi guys, I see low activity here, should I worry? is this repo stale?

**Comment by Romanchuk** [comment]
@scastaldi Hi, low activity here because of one reason -  there was nothing to update)
I see i18next v.19 relesed, i will upadte support soon

**Comment by scastaldi** [comment]
I did struggle to find an issue upgrading from Angular 7 to Angular 8 
Please add it to the documentation, and thank you for your work on angular-i18next

Need to change imports from:
```
import * as i18nextXHRBackend from 'i18next-xhr-backend';
import * as i18nextLanguageDetector from 'i18next-browser-languagedetector';
```
To:
```
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
```

**Comment by Romanchuk** [comment]
@scastaldi Thank you! Oh, i did struggle with that thing. With importing i18next-xhr-backend v3. Ok, i'll fix it.

**Comment by Romanchuk** [comment]
https://github.com/Romanchuk/angular-i18next/commit/46cd56558699e43e5d0216642adf68048df32de7
