### ISSUE TITLE
Trying to use the Pipe in submodules

### ISSUE THREAD

**Issue by httpete** [Romanchuk/angular-i18next#4]
Hi,
I have registered your module with forRoot() as you specify and it works in the parent component fine, but won't work in one of the subModules. Do I need to import the module again somewhere else?

**Comment by Romanchuk** [comment]
@httpete Hello,
Yes, you are right. You need to specify I18NextModule.forRoot() once in your AppModule (root module). And then you need to import only I18NextModule to submodules.

For example you can have your feature modules defined in routing (in lazy and non-lazy way):

```
export const appRoutes: Routes = [
  { path: 'request_list', loadChildren: 'app/features/request_list/RequestListFeatureModule#RequestListFeatureModule' },
  { path: 'api01', loadChildren: () => Api01FeatureModule }
];
```
Than each of these child modules/submodules must import I18NextModule (without .root()) overwise submodule component template would not find i18next pipe and you will get an error:

`The pipe 'i18next' could not be found`

**Comment by httpete** [comment]
Thank you Romanchuk, it works perfectly. I am used to global magic with Angular 1, which had a looser module dependency setup. I have to explicitly import it in each submodule, and it declares what it needs which is proper for portability. 
I also built a filter|pipe in Angular 1 to wrap i18next.format. it looked like this. Can you expose this pipe as well in a future version? It doesn't do much, just exposes it to angular, and lets the user configure the i18next formatting api on their own in the init()

`      /* i18next  format filter */
        this.native.filter('i18nextFormat', ['$i18next', function ($i18next) {
            return function (key, formatType: string) {
                return $i18next.i18n.format(key, formatType);
            };
        }])`

**Comment by Romanchuk** [comment]
@httpete I'm glad to help you.

Oh, i actualy missed this format feature (_introduced in v8.4.0_). I will surely think about it! Thank you for suggestion.

At the moment it is possible to use few predefined formatters in i18next pipe with 'case' option: 
`'key | i18next: { case: 'uppercase' }'`

```
private postProcessCase(value: string, wordCase: string): string {
      if (!value) return value;
      switch (wordCase) {
        case null:
        case 'none':
          return value;
        case 'upper':
        case 'uppercase':
          return value.toUpperCase();
        case 'lower':
        case 'lowercase':
          return value.toLowerCase();
        case 'cap':
        case 'capitalize':
          return value.charAt(0).toUpperCase() + value.slice(1);
        default:
          return value;
    }
  }
```

Often you need just capitalize fist letter for that case you can use i18nextCap pipe without 'case' option.

**Comment by Romanchuk** [comment]
@httpete 
angular-i18next 3.0.0-alpha just published
Added native i18next format support and I18NextFormatPipe.
You are welcome to test it =)
Complete version info and status: https://github.com/romanchuk/angular-i18next#roadmap-version-3
