### ISSUE TITLE
Add Angular 9 support

### ISSUE THREAD

**Issue by Romanchuk** [Romanchuk/angular-i18next#44]

**Comment by nikolay-govorov** [comment]
Thank you for your project, it's wonderful.

I use `angular-i18next` together with Angular 9, and have no problems. What improvements are required to start officially supporting the new Angular?

Can I help you upgrade to the new version?

**Comment by Romanchuk** [comment]
@nikolay-govorov It should, but i need to raise up dependencies versions at least.

**Comment by nikolay-govorov** [comment]
Now you can support this Wish from https://beerpay.io/Romanchuk/angular-i18next/wishes/5e43f131a2ad1d2f815c0d42

🍻 Cheers!

**Comment by Romanchuk** [comment]
@nikolay-govorov Hi, thanks!
Just released version 8.0.0, you may try it. Next i'm going to update angular-i18next-message.

About beerpay: this is a cool service, but i just realized that i cannot payout from it... No support Russia by Stripe. So decline your wish, hope you don't lose your money. And i'm moving to paypal

**Comment by Romanchuk** [comment]
**angular-i18next-message@3.0.1** also published!
