### ISSUE TITLE
Missing function overloading in ITranslationService

### ISSUE THREAD

**Issue by shadizar128** [Romanchuk/angular-i18next#46]
The translation method is missing one of it's forms where it accepts a default value.
From i18next we can see the definition of the TFunction as:

> export interface TFunction {
>   // basic usage
>   <
>     TResult extends TFunctionResult = string,
>     TKeys extends TFunctionKeys = string,
>     TInterpolationMap extends object = StringMap
>   \>(
>     key: TKeys | TKeys[],
>     options?: TOptions<TInterpolationMap> | string,
>   ): TResult;
>   // overloaded usage
>   \<
>     TResult extends TFunctionResult = string,
>     TKeys extends TFunctionKeys = string,
>     TInterpolationMap extends object = StringMap
>   \>(
>     key: TKeys | TKeys[],
>     defaultValue?: string,
>     options?: TOptions<TInterpolationMap> | string,
>   ): TResult;
> }

**Comment by Romanchuk** [comment]
@shadizar128 Thank you for PR, again!
I have changed your code a bit and also improved typings in version 9.0.0
