### ISSUE TITLE
i18next for t.options not working anymore in 9.0.0

### ISSUE THREAD

**Issue by tmtron** [Romanchuk/angular-i18next#48]
Translating` t.options` like this: 
```
`{{ 'operation.editTarget' | i18nextCap: { target: 'control.title' | i18next } }}
```
was working in versions `7.0.0` and `8.0.1` - but does not work anymore in `9.0.0`.

Note: we want to pass a translated text to the `target` variable of `operation.editTarget`.

Is this a regression, or is there now another way to do this?

Other versions:
* angular 9
* i18next: `19.3.1`

**Comment by Romanchuk** [comment]
Hello, what is 'operation.editTarget' value?

**Comment by tmtron** [comment]
note: it seems that the realease version `8.1.0` is gone!  
Anyway, I've created an example with version `7.0.0`

In [Stackblitz-Example with version 7.0.0](https://stackblitz.com/edit/ng-i18next-48-7?file=src%2Fapp%2Fexample-component.html) the text is okay:

![2020-02-23_18h02_17](https://user-images.githubusercontent.com/20422904/75116264-c03b8300-5666-11ea-8707-7cb47b7ebb22.png)

In [Stackblitz-Example with version 9.0.0](https://stackblitz.com/edit/ng-i18next-48-9?file=src/app/example-component.html), the text is not okay; the parameter `target` is missing:  

![image](https://user-images.githubusercontent.com/20422904/75116271-d77a7080-5666-11ea-8eca-02a085c03a73.png)

The 2 examples are the same, except for the `angualr-i18next` versions.

In the console of version v9.0.0 we see a warning
```
i18next::interpolator: missed to pass in variable target for interpolating edit {{target}}
```

**Comment by pheinicke** [comment]
I can confirm this issue. Upgraded from 7.0.0 to 9.0.0. Options are no longer working.

```
"appName": "${context}",
"appName_task": "Task",
"appName_news": "News",
...
```

`'appName' | i18next:{context:'news'}` was translated correctly to "News" in 7.0.0, now (9.0.0) it's "${context}"

**Comment by Romanchuk** [comment]
@pheinicke @tmtron Thank you both, i'll take it to work today.
You can safely downgrade to 7 or 8 version until i fix it.

**Comment by Romanchuk** [comment]
@pheinicke @tmtron Fixed in 9.0.1. Check it out!

**Comment by pheinicke** [comment]
It's working for me. Thanks for the quick fix!

**Comment by tmtron** [comment]
Working for me. Thanks for the fast response time!
