### ISSUE TITLE
Using multiple namespaces

### ISSUE THREAD

**Issue by plakak** [Romanchuk/angular-i18next#5]
I don't see an option to include multiple namespaces in a module. When I was using i18next in React I could simply do `['base', 'common', 'component']` to include three namespaces.

Is this possible with angular-i18next? Could it be?

**Comment by Romanchuk** [comment]
@plakak Hello!
The thing is a feature to dynamicaly load namespaces for module/component is not implemented yet.

At current version you can provide ONE namespace as I18NEXT_NAMESPACE token to your module/component and pipe will automatically prefix your keys. For expample if your namespace is "common" and key is "key" it will call translation method with ["common:key", "key"] params. Of course init options must include this namespace.

I'm going to add this feature to roadmap.

**Comment by plakak** [comment]
Thanks for the reply @Romanchuk. Great to see that coming.
The thing is that I have a `common` namespace for things like: `Submit` button, `Go Back` button etc, while in a component I'd like to have translation specific to that component. So in my `warranty-form.json` I don't have to include one more time translation for submit button since it's already in `common.json`. That's for me is the main strength of i18next compared to similar libraries. Is there any way to achieve it right now? Something like a common namespace for all components while being able to namespace each component individually?

**Comment by Romanchuk** [comment]
@plakak Yes, you can do it. Actually i did it in the real app.
I had default namespace (translation.json) that had common localization dictionaries and child modules with their own namespaces. 

i18next options:

```
ns: [
    'translation', // this is default namespace with common keys
    'validation',
    'error',
    'select2', // custom component namespace
    'feature.warranty', // feature 1 namespace (WarrantyFeatureModule)
    'feature.api01', // feature 2 namespace
    'FileApi'  // custom component namespace
  ]

```
In WarrantyFeatureModule module:
```
@NgModule({
  providers: [
 {
      provide: I18NEXT_NAMESPACE,
      useValue: 'feature.warranty'
    }
....
export class WarrantyFeatureModule{

}
})
```
I18NEXT_NAMESPACE this will apply to i18next pipe in Api01FeatureModule child context and will treat key (example 'submit_title') as array of keys ['feature.warranty:submit_title', 'submit_title'] and i18next will search a key in 
feature.warranty.json file (this feature specific dictionaries)  and if there is no key 'technical_contact_description' found, it will search in 'translation.json' file.

Also you can provide I18NEXT_NAMESPACE to your custom component and it will work the same way.
Remember i18next pipe will get the latest I18NEXT_NAMESPACE value provided in it's component tree.



i18next pipe checks only one specific namespace and one common/default namespace. So you can have only one common localization dictionary and many specific for module/component.


Finally to make it more scalable (Considering your initial question)  i plan to:

1. make I18NEXT_NAMESPACE to provide arrays of namespaces
2. dynamically load these namespaces on bootstraping module/component

**Comment by Romanchuk** [comment]
@plakak Also, currently i'm working at demo app, that will include all possible features providing in current version. There would be example of using I18NEXT_NAMESPACE.

**Comment by plakak** [comment]
Ah, OK - so the first `ns` in the config array is taken as fallback/default. Cool, I can live with that until multiple namespaces are possible. Thanks, @Romanchuk :+1:

**Comment by Romanchuk** [comment]
>  so the first ns in the config array is taken as fallback/default.

It's not quite right. [i18next docs](https://www.i18next.com/configuration-options.html) says:
Default ns setting up by 'defaultNS' option on i18next init. And it's default value is 'translation'. 
Also there is 'fallbackNS' you might want to set up (i never used it)

**Comment by Romanchuk** [comment]
@plakak 
angular-i18next 3.0.0-alpha just published
Added lazy namespace loading
You are welcome to test it =)
Complete version info and status: https://github.com/romanchuk/angular-i18next#roadmap-version-3

**Comment by Romanchuk** [comment]
angular-i18next v3.0.0 relesed
