### ISSUE TITLE
Update peerDependency of i18next

### ISSUE THREAD

**Issue by Laberbear** [Romanchuk/angular-i18next#50]
Currently doing some Angular updates in our application and updated angular-i18next.

Seems like the specified peerDependency of i18next is not valid anymore.
We were using     "i18next": "^11.6.0", and ran into build errors from angular-i18next.
Updating to the latest (19.4.3) fixed this.

**Comment by Romanchuk** [comment]
@Laberbear Hmm.. strange, whats angular version are you using?

**Comment by Laberbear** [comment]
9.1.2

**Comment by mlada** [comment]
I use 9.1.3, has the same problem after and before updated i18next

**Comment by Romanchuk** [comment]
Updated demo (angular: 9.1.6, i18next: 19.4.4). It works without problem.
https://romanchuk.github.io/angular-i18next-demo/

i18next in most cases is safe to update, please use latest version, if you have problems.

I'm going to raise up i18next dep in future version (as soon as angular 10 comes out): https://github.com/Romanchuk/angular-i18next/issues/52
