### ISSUE TITLE
i18nextpipe.d.ts is not exported from angular-i18next

### ISSUE THREAD

**Issue by mlada** [Romanchuk/angular-i18next#51]
"@angular/core": "^9.1.5",
"angular-i18next": "^9.0.1",
"i18next": "^19.4.3", 

Can`t build project

ERROR in Symbol I18NextPipe declared in .../node_modules/angular-i18next/i18nextpipe.d.ts is not exported from angular-i18next (import into ../libs/layer-components/src/lib/header/header.component.ts)

**Comment by Romanchuk** [comment]
@mlada What's your import string?

**Comment by mlada** [comment]
@Romanchuk I don't have I18NextPipe imports. 
Problem was in andgular 9.1.5, build ivy was broken. In 9.1.6 problem solved. 
https://github.com/angular/angular/issues/36992

**Comment by Romanchuk** [comment]
@mlada  

> 9.1.5, build ivy was broken.
Wow, thx for information
