### ISSUE TITLE
Angular 10

### ISSUE THREAD

**Issue by Romanchuk** [Romanchuk/angular-i18next#52]
As soon as angular 10 releases:
- Update angular deps
- Raise up i18next dependecy to >= 19

**Comment by MaxSassen** [comment]
Hi @Romanchuk angular 10 has been released, can we update the package?

**Comment by Romanchuk** [comment]
@MaxSassen I'll start work on it in next monday

**Comment by Romanchuk** [comment]
@MaxSassen  angular-i18next **10.0.0 published**

**Comment by MaxSassen** [comment]
thanks for your good work :D @Romanchuk
