### ISSUE TITLE
Using with AOT builds

### ISSUE THREAD

**Issue by Antarus66** [Romanchuk/angular-i18next#56]
Hi!
Thank you for your efforts of integration i18next with Angular.

The documentation of this library says that AOT is supported. We are trying to use it with AOT build of our application and got an error:

![image](https://user-images.githubusercontent.com/7629380/87644155-6db54d00-c754-11ea-9347-7967ba33b065.png)

Could you please add a short guide how to set it up?

**Comment by Romanchuk** [comment]
@Antarus66 Hello, l'm almost sure this is not AOT related issue. Make sure browser loaded your locale files
