### ISSUE TITLE
Update package to support Angular 5.0.0

### ISSUE THREAD

**Issue by romko391** [Romanchuk/angular-i18next#6]
Need replacing `OpaqueToken` by `InjectionToken<T>` as `OpaqueToken` is no longer available.

**Comment by httpete** [comment]
I changed this to this in: the I18NEXT_TOKENS.d.ts

import { InjectionToken } from '@angular/core';
export declare const I18NEXT_SCOPE: InjectionToken<any>;
export declare const I18NEXT_NAMESPACE: InjectionToken<any>;
export declare const I18NEXT_SERVICE: InjectionToken<any>;

**Comment by romko391** [comment]
@httpete I also did the same, but I'm building my prod on AWS, so it pulls all packages all the time and I have no control over it.
Actually, I already updated the project but I don't have permission to push a branch and therefore to create a pull request.
I hope some of the existing contributors will grant it to me or just update by theirself.

**Comment by httpete** [comment]
thanks - do you think it will go out soon? Not sure what you mean by push and pull.

**Comment by romko391** [comment]
I hope so. But it depends on repository owner.
Under pull I mean I'm using AWS CodePipeline which automates build process (ng b --prod) which installs NPM pkgs so it pulls old version from here which fails on build

**Comment by Romanchuk** [comment]
@httpete @romko391 I'm planning to update package at this weekend.

**Comment by Romanchuk** [comment]
@romko391 @httpete 
Just updated a package v2.0.0-beta2. You can try now:
`npm install angular-i18next@beta --save`
I'm going to publish release package, if you don't have issues.

**Comment by romko391** [comment]
@Romanchuk 2.0-beta works fine for me

**Comment by httpete** [comment]
beta works fine for me thanks! I am using angular 5.0.1.

**Comment by Romanchuk** [comment]
angular-i18next v2.0.0 released
