### ISSUE TITLE
ERROR in node_modules/angular-i18next/I18NextService.d.ts(11,9): error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by PradneshShinde** [Romanchuk/angular-i18next#67]
There's  get accessor which is giving an error, during` ng server` 
![image](https://user-images.githubusercontent.com/37576222/103739694-f46c2800-501b-11eb-9784-391928cdcfa3.png)
 
But when i remove the get accessor from the  option() :any.
![image](https://user-images.githubusercontent.com/37576222/103740341-0e5a3a80-501d-11eb-8a8f-1dc563bce233.png)

Then the angular code complies successfully.
Does this manual change feasible.
Version i'm using for the package `angular-i18next`  is `10.0.1 `

**Comment by Romanchuk** [comment]
@PradneshShinde hello, what typescript version do you use?

**Comment by Romanchuk** [comment]
Looks like you use an old typescript version

**Comment by PradneshShinde** [comment]
3.2.2 @Romanchuk  , a bit late to reply

**Comment by Romanchuk** [comment]
@PradneshShinde 
As i assumed you have old typescript version
Update typescript in-project version to 3.9+ version or downgrade angular-i18next

**Comment by PradneshShinde** [comment]
@Romanchuk , if i'm using typescript 3.4.5 currently, what should be the angular-i18-next package version ??

**Comment by Romanchuk** [comment]
@PradneshShinde It's about... v7.2.0 +

**Comment by Romanchuk** [comment]
@PradneshShinde you need to dive to package.json file history to figure it out
