### ISSUE TITLE
i18nextEagerPipe does not take into account PipeOptions changes

### ISSUE THREAD

**Issue by wawyed** [Romanchuk/angular-i18next#68]
If you want to only change the `PipeOptions`, for example you want to change an interpolation value the pipe does not retrieve the translation again and it rather uses the now incorrect cached value.

The expected behaviour is that the line below would also check for at least the `options` object reference having changed.

https://github.com/Romanchuk/angular-i18next/blob/e23ab0dc3160acec7bb1ee908538cc03833e8cdc/src/I18NextEagerPipe.ts#L38

**Comment by Romanchuk** [comment]
@wawyed Thx for PR!
I have released beta version **10.1.0-0**, please test it, if it is OK, than i'll release stable version

**Comment by wawyed** [comment]
No problem. That seems to work as expected in my app :). Thank you.

**Comment by Romanchuk** [comment]
**angular-i18next 10.1.0** published!
