### ISSUE TITLE
Update to Angular 13

### ISSUE THREAD

**Issue by elgervb** [Romanchuk/angular-i18next#76]

**Comment by Romanchuk** [comment]
Coming soon

**Comment by elgervb** [comment]
I've already made a fork in which I update to angular 13, but I cannot seem to get the tests working.
Library works great, I've tested it in my app by npm linking it to the updated library.

**Comment by Romanchuk** [comment]
@elgervb I'm going to update lib at this weekend

**Comment by Romanchuk** [comment]
Work in progress, having problems with test infrastructure

**Comment by DanielRivers** [comment]
Hi,

Is there an update on the progress of this?

**Comment by MaxSassen** [comment]
Hehe was thinking the same :P any progress?

**Comment by Romanchuk** [comment]
Guys, please tryout. I have no time to test it.

`angular-i18next@11.0.0-0`
or 
`angular-i18next@beta`

I have migrated repo to Nx, jest, angular 13.
It takes a lot more time than i expected, i'll close this issue after i make all tests run.

**Comment by Romanchuk** [comment]
Please start the repo, it might help to apply sponsorship and spend more time on this project

**Comment by MaxSassen** [comment]
> Guys, please tryout. I have no time to test it.
> 
> `angular-i18next@11.0.0-0` or `angular-i18next@beta`
> 
> I have migrated repo to Nx, jest, angular 13. It takes a lot more time than i expected, i'll close this issue after i make all tests run.

just wondering, did the setup changed? getting some errors:
![image](https://user-images.githubusercontent.com/6112704/148454901-a4842695-390e-4412-89de-5818a58d32fb.png)

but the install of `angular-i18next@11.0.0-0` succeeded

**Comment by elgervb** [comment]
@Romanchuk I've installed `angular-i18next@11.0.0-0` and tested it.. Seems to work like a charm ;-)

**Comment by Romanchuk** [comment]
Since no one has broblems with beta
Stable version released: **angular-i18next@11.0.0**

Still working at migrating tests to jest
