### ISSUE TITLE
whitelist is not in i18n.InitOptions

### ISSUE THREAD

**Issue by tomtrapp** [Romanchuk/angular-i18next#81]
When setting up a new project with angular-i18next, the build fails because whitelist is not a property of i18n.InitOptions

**Comment by Romanchuk** [comment]
@tomtrapp 
whitelist property has removed in i18next v21 (https://www.i18next.com/misc/migration-guide#removed-deprecated)

> 
> The old [deprecated whitelist options](https://github.com/i18next/i18next/issues/1466) and functions have been definitively removed.
> 
> - rename option whitelist to supportedLngs
> - rename option nonExpicitWhitelist to nonExplicitSupportedLngs
> - rename function languageUtils.isWhitelisted to languageUtils.isSupportedCode

angular-i18next relates to your i18next version and its types

**Comment by Romanchuk** [comment]
Check your versions and correct i18next config according to its version

**Comment by tomtrapp** [comment]
Then please update your documentation step 3 under Installation :)
There is whitelist still referenced
