### ISSUE TITLE
Upgrading to ^11.0.0 is not working for angular 13

### ISSUE THREAD

**Issue by Yogaraju** [Romanchuk/angular-i18next#82]
I have upgraded to version ^11.0.0 and angular to v13 and I am using i18next-http-backend. When I run unit testcases, they are failing by throwing the following error
`Error: ASSERTION ERROR: Expected localId to be defined [Expected=> null != undefined <=Actual]`

i18next-browser-languagedetector also been used as suggested but still the issue resides.

The issue was not there with previous version of angular-i18next 
@Romanchuk @tobstarr

**Comment by Romanchuk** [comment]
@Yogaraju What tests are you running?

**Comment by Yogaraju** [comment]
I am running unit test cases in angular. If LOCAL_ID is commented inside I18N_PROVIDERS array then it works fine otherwise the test will through the error.

The array is as below
export const I18N_PROVIDERS = [
{
    provide: APP_INITIALIZER,
    useFactory: appInit,
    deps: [I18NEXT_SERVICE],
    multi: true
},
{
    provide: LOCALE_ID,
    deps: [I18NEXT_SERVICE],
    useFactory: localeIdFactory
}];

**Comment by Romanchuk** [comment]
@Yogaraju You need to aware that angular 13 now using .mjs modules. So there are some problems with test engines after moving to angular 13. I got it with cypress and karma
