### ISSUE TITLE
upgrade to angular v.14

### ISSUE THREAD

**Issue by alexander-matveev** [Romanchuk/angular-i18next#84]
when I try to upgrade my angular version from 13 to 14 I get this error

Fetching dependency metadata from registry...
                  Package "angular-i18next" has an incompatible peer dependency to "@angular/common" (requires ">=10.0.0 <13.0.0" (extended), would install "14.0.0").
                  Package "angular-i18next" has an incompatible peer dependency to "@angular/core" (requires ">=10.0.0 <13.0.0" (extended), would install "14.0.0").
                  Package "angular-i18next" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=10.0.0 <13.0.0" (extended), would install "14.0.0").

× Migration failed: Incompatible peer dependencies found.

Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.

**Comment by Romanchuk** [comment]
@alexander-matveev Sure, package needs to be updated
I'll do it in about a week

**Comment by Romanchuk** [comment]
https://github.com/Romanchuk/angular-i18next/releases/tag/v14.0.0-0

**Comment by Romanchuk** [comment]
@alexander-matveev Good day!  Beta version 14.0.0-0 released. Try it and tell me if it is okay

**Comment by alexander-matveev** [comment]
@Romanchuk looks like it's works for me
