### ISSUE TITLE
Builtin formatters wont work

### ISSUE THREAD

**Issue by faculezcano** [Romanchuk/angular-i18next#87]
When trying to use for instance `currency` formatter it throws an error because options is not being passed to `i18next.format(...)` function.

I've made a PR, please let me know if i have to make changes.

https://github.com/Romanchuk/angular-i18next/pull/86

Best

**Comment by Romanchuk** [comment]
Thanks, mate! Finally got a minute to merge it

**Comment by Romanchuk** [comment]
Fixed at angular-i18next **14.1.0**
