### ISSUE TITLE
Node 16 support 

### ISSUE THREAD

**Issue by francisedulab** [Romanchuk/angular-i18next#93]
Hi we have an angular project which runs only on node 16 , we are unable to install this library on the angular 13 project using --force command installs but its unable to compile is there any workaround possible?

**Comment by Romanchuk** [comment]
There is no any restrictions about nodejs.
I ran it on 16.
Please check your compile setup.

**Comment by Romanchuk** [comment]
@francisedulab You might catch this error: [#91](https://github.com/Romanchuk/angular-i18next/issues/91). It is now fixed
